//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektiOrari.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<chatUser> chatUsers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<KerkesaPerNderrim> KerkesaPerNderrims { get; set; }
        public virtual DbSet<Lenda> Lendas { get; set; }
        public virtual DbSet<LendetEZgjedhura> LendetEZgjedhuras { get; set; }
        public virtual DbSet<Ligjeruesit> Ligjeruesits { get; set; }
        public virtual DbSet<Orari> Oraris { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
