//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektiOrari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int idFeedback { get; set; }
        public Nullable<int> Studenti { get; set; }
        public Nullable<int> Lenda { get; set; }
        public string Mesazhi { get; set; }
        public string MesazhiRreth { get; set; }
        public Nullable<System.DateTime> Data_e_feedback { get; set; }
    
        public virtual User User { get; set; }
    }
}
