//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektiOrari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LendetEZgjedhura
    {
        public int idLendaZgjedhur { get; set; }
        public int Studenti { get; set; }
        public int idLigjeruesi { get; set; }
        public int Semestri { get; set; }
        public Nullable<System.DateTime> Data_e_zgjedhjes { get; set; }
    
        public virtual User User { get; set; }
    }
}
