//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektiOrari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orari
    {
        public int IDOrari { get; set; }
        public Nullable<int> IDLigjeruesi { get; set; }
        public string Emri_Numri_i_salles { get; set; }
        public string Dita { get; set; }
        public System.TimeSpan OraFillimit { get; set; }
        public System.TimeSpan OraMbarimit { get; set; }
        public int Semestri { get; set; }
        public string Drejtimi { get; set; }
    }
}
